# Generated by Django 4.2 on 2023-05-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
